import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "saraswati-music",
    name: "15\" The Saraswati - Goddess Of Music | Super White Makrana Marble",
    deity: "Saraswati — The Goddess of Knowledge & Arts",
    price: 100065,
    originalPrice: 100065,
    material: "Super White Makrana Marble",
    height: "15 inches",
    weight: "11 kg",
    description: "15\" The Saraswati - Goddess Of Music | Super White Makrana Marble Figurine",
    longDescription: "An exquisite 15-inch (38 cm) statue of Goddess Saraswati, beautifully playing the Veena. Handcrafted from premium Super White Makrana Marble, this divine 11 kg figurine features intricate stonework and gold detailing, capturing the pure essence of the Goddess of Knowledge, Music, and Arts.",
    images: [
      "/products/saraswati-hero.png",
      "/products/saraswati-1.png",
      "/products/saraswati-2.jpg",
      "/products/saraswati-3.png",
      "/products/saraswati-4.png",
      "/products/saraswati-5.jpg"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Super White Makrana Marble with Gold",
    origin: "MADE IN INDIA",
    features: [
      "Super White Makrana Marble",
      "Height: 38 cm (15 inch)",
      "Width: 25.5 cm (10 inch)",
      "Depth: 12.5 cm (5 inch)",
      "Weight: 11 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "nandi-auspicious",
    name: "Nandi: An Auspicious Presence",
    deity: "Nandi — The Sacred Bull",
    price: 140700,
    originalPrice: 140700,
    material: "White Marble Statue",
    height: "16.5 inches",
    weight: "56.55 kg",
    description: "Nandi: An Auspicious Presence | 16.5 inch White Marble Statue",
    longDescription: "A glorious 16.5-inch (42 cm) statue of Nandi, the sacred bull and devoted vahana of Lord Shiva. Meticulously carved from pristine white marble, this 56.55 kg murti radiates peace, devotion, and auspiciousness, making it a perfect addition to any divine altar.",
    images: [
      "/products/nandi-hero.png",
      "/products/nandi-1.png",
      "/products/nandi-2.png",
      "/products/nandi-3.png",
      "/products/nandi-4.png",
      "/products/nandi-5.png"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Polished White Marble",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 42 cm (16.5 inch)",
      "Width: 56 cm (22 inch)",
      "Depth: 28 cm (11 inch)",
      "Weight: 56.55 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "durga-maa-large",
    name: "39\" Large Durga Maa Statue - The Warrior Form Of Parvati",
    deity: "Durga — The Invincible Force",
    price: 520380,
    originalPrice: 520380,
    material: "Super White Makrana Marble",
    height: "39 inches",
    weight: "140 kg",
    description: "39\" Large Durga Maa Statue | Super White Makrana Marble",
    longDescription: "A massive and awe-inspiring 39-inch (99 cm) marble statue of Goddess Durga riding her fierce lion. Crafted from premium Super White Makrana Marble, this 140 kg masterpiece intricately depicts the Warrior Form of Parvati with Her eight arms, each holding a divine weapon to protect the universe.",
    images: [
      "/products/durga-maa-hero.png",
      "/products/durga-maa-1.jpg",
      "/products/durga-maa-2.jpg",
      "/products/durga-maa-3.jpg",
      "/products/durga-maa-4.jpg",
      "/products/durga-maa-5.png"
    ],
    rating: 5.0,
    reviews: 2,
    inStock: true,
    badge: "Premium",
    category: "Marble",
    finish: "Super White Makrana Marble with Gold",
    origin: "MADE IN INDIA",
    features: [
      "Super White Makrana Marble",
      "Height: 99 cm (39 inch)",
      "Width: 76 cm (30 inch)",
      "Depth: 20.5 cm (8 inch)",
      "Weight: 140 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "vishnu-lakshmi-set",
    name: "18\" Standing Vishnu - Lakshmi in Blessing Gesture | Set of Two",
    deity: "Vishnu & Lakshmi",
    price: 160125,
    originalPrice: 160125,
    material: "White Marble Statues",
    height: "18 inches",
    weight: "Handmade",
    description: "Vishnu and Lakshmi Set of Two | 18 inch White Marble Statues",
    longDescription: "A breathtaking pair of white marble statues depicting Lord Vishnu and Goddess Lakshmi in a supreme blessing gesture. Standing at 18 inches and 17 inches respectively, these handcrafted murtis feature exquisite gold detailing and intricate stonework, representing the ultimate divine union of preservation and prosperity.",
    images: [
      "/products/vishnu-lakshmi-set-hero.png",
      "/products/vishnu-lakshmi-set-1.jpg",
      "/products/vishnu-lakshmi-set-2.png",
      "/products/vishnu-lakshmi-set-3.jpg",
      "/products/vishnu-lakshmi-set-4.jpg",
      "/products/vishnu-lakshmi-set-5.jpg"
    ],
    rating: 5.0,
    reviews: 6,
    inStock: true,
    badge: "Masterpiece Set",
    category: "Marble",
    finish: "Hand-painted White Marble with Gold",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statues",
      "Vishnu: 18\" H x 7.5\" W x 4\" D",
      "Lakshmi: 17\" H x 7\" W x 4\" D",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "krishna-lotus-throne",
    name: "14\" Murli Manohara Krishna Marble Statue on a Lotus Throne",
    deity: "Krishna — The Divine Flutist",
    price: 63000,
    originalPrice: 63000,
    material: "Marble Statue",
    height: "14.8 inches",
    weight: "13.11 kg",
    description: "Murli Manohara Krishna on Lotus Throne | 14.8 inch Marble Statue",
    longDescription: "A breathtaking 14.8-inch (37.5 cm) marble statue of Murli Manohara Krishna gracefully seated on a vibrant lotus throne. Every detail, from the divine peacock feather crown to the delicately held flute, is masterfully hand-painted to capture the enchanting beauty and eternal joy of the Lord.",
    images: [
      "/products/krishna-lotus-hero.png",
      "/products/krishna-lotus-1.png",
      "/products/krishna-lotus-2.png",
      "/products/krishna-lotus-3.jpg",
      "/products/krishna-lotus-4.jpg"
    ],
    rating: 5.0,
    reviews: 4,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted Marble",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 37.5 cm (14.8 inch)",
      "Width: 26.5 cm (10.5 inch)",
      "Depth: 18.5 cm (7.25 inch)",
      "Weight: 13.11 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "shri-krishna-marble",
    name: "Shri Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 47250,
    originalPrice: 47250,
    material: "Marble Statue",
    height: "15 inches",
    weight: "3.70 kg",
    description: "Shri Krishna | 15 inch White Marble Statue",
    longDescription: "A glorious 15-inch (38 cm) white marble statue of Shri Krishna playing his divine flute. Expertly carved and adorned with beautiful painted details and delicate stones, this enchanting murti perfectly captures the supreme love, joy, and magnetism of the Lord.",
    images: [
      "/products/shri-krishna-hero.png",
      "/products/shri-krishna-1.png"
    ],
    rating: 5.0,
    reviews: 3,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Hand-painted White Marble with Stones",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 38 cm (15 inch)",
      "Width: 7.5 cm (3 inch)",
      "Depth: 20.5 cm (8 inch)",
      "Weight: 3.70 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "parvati-serpent",
    name: "Goddess Parvati with Five-hooded Serpent Canopying Atop",
    deity: "Parvati — The Divine Mother",
    price: 10500,
    originalPrice: 10500,
    material: "Stone Statue from Mahabalipuram",
    height: "8.5 inches",
    weight: "Handmade",
    description: "Goddess Parvati with Five-hooded Serpent | 8.5 inch Stone Statue",
    longDescription: "An exquisite 8.5-inch (21.5 cm) stone statue of Goddess Parvati, handcrafted in Mahabalipuram. This unique murti features the Divine Mother seated gracefully with a magnificent five-hooded serpent canopying atop her head, symbolizing divine protection and cosmic energy.",
    images: [
      "/products/parvati-serpent-hero.png",
      "/products/parvati-serpent-1.jpg",
      "/products/parvati-serpent-2.png"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Just Added",
    category: "Stone",
    finish: "Hand-carved Stone",
    origin: "MADE IN INDIA",
    features: [
      "Stone Statue from Mahabalipuram",
      "Height: 21.5 cm (8.5 inch)",
      "Width: 14 cm (5.5 inch)",
      "Depth: 7.5 cm (3 inch)",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "tirupati-balaji",
    name: "6\" Tirupati Balaji (Venkateshvara)",
    deity: "Venkateshvara — Lord of the Universe",
    price: 14175,
    originalPrice: 14175,
    material: "Black Stone",
    height: "6 inches",
    weight: "Handmade",
    description: "6\" Tirupati Balaji (Venkateshvara) | Intricate Black Stone Murti",
    longDescription: "A beautifully detailed 6-inch black stone murti of Tirupati Balaji (Lord Venkateshvara). Hand-carved with astonishing precision, this sacred idol showcases the Lord in his iconic standing posture, adorned with a glorious crown and jewels, ready to shower blessings upon your home.",
    images: [
      "/products/tirupati-balaji-hero.png",
      "/products/tirupati-balaji-1.jpg",
      "/products/tirupati-balaji-2.jpg",
      "/products/tirupati-balaji-3.jpg",
      "/products/tirupati-balaji-4.jpg"
    ],
    rating: 5.0,
    reviews: 2,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Intricate Black Stone Polish",
    origin: "MADE IN INDIA",
    features: [
      "Black Stone Statue",
      "Height: 6 inches",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "hanuman-sanjeevani",
    name: "Hanuman Ji Carrying Mount Dron of Sanjeevani Herbs",
    deity: "Hanuman — The Supreme Devotee",
    price: 95865,
    originalPrice: 95865,
    material: "White Marble",
    height: "19.5 inches",
    weight: "10 kg",
    description: "Hanuman Ji Carrying Mount Dron of Sanjeevani Herbs | 19.5 inch White Marble Statue",
    longDescription: "A glorious 19.5-inch (49.5 cm) white marble statue depicting Lord Hanuman flying with Mount Dron to bring the life-saving Sanjeevani herbs. Handcrafted with exquisite detailing, painted with vibrant colors, and adorned with delicate stones, this murti perfectly captures the strength, devotion, and urgency of the Supreme Devotee.",
    images: [
      "/products/hanuman-sanjeevani-hero.png",
      "/products/hanuman-sanjeevani-1.png"
    ],
    rating: 4.0,
    reviews: 1,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted White Marble with Stones",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 49.5 cm (19.5 inch)",
      "Width: 23 cm (9 inch)",
      "Depth: 7.5 cm (3 inch)",
      "Weight: 10 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "vishnu-chaturbhuja",
    name: "Chaturbhuja Vishnu",
    deity: "Vishnu — The Preserver",
    price: 85365,
    originalPrice: 85365,
    material: "White Marble",
    height: "14.7 inches",
    weight: "3.50 kg",
    description: "Chaturbhuja Vishnu | 14.7 inch White Marble Statue",
    longDescription: "A magnificent 14.7-inch (37.5 cm) white marble statue of Lord Vishnu in his four-armed (Chaturbhuja) form, holding the conch, discus, mace, and lotus. This divine murti is adorned with exquisite detailing and represents the supreme preserver of the universe.",
    images: [
      "/products/vishnu-chaturbhuja-hero.png",
      "/products/vishnu-chaturbhuja-1.png",
      "/products/vishnu-chaturbhuja-2.png"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-painted White Marble with Gold Details",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 37.5 cm (14.7 inch)",
      "Width: 7.5 cm (3 inch)",
      "Depth: 17 cm (6.7 inch)",
      "Weight: 3.50 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "krishna-omnibenevolent",
    name: "The Omnibenevolent Gaze of Lord Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 73920,
    originalPrice: 73920,
    material: "White Marble",
    height: "24 inches",
    weight: "28.20 kg",
    description: "The Omnibenevolent Gaze of Lord Krishna | 24 inch White Marble Statue",
    longDescription: "A breathtaking 24-inch (61 cm) white marble statue of Lord Krishna playing his divine flute. Known as 'The Omnibenevolent Gaze', this masterpiece is adorned with intricate golden painting, sparkling jewels, and a majestic crown. The statue weighs 28.20 kg, making it a substantial and deeply commanding centerpiece for any spiritual space.",
    images: [
      "/products/krishna-omnibenevolent-hero.jpg",
      "/products/krishna-omnibenevolent-1.jpg",
      "/products/krishna-omnibenevolent-2.jpg",
      "/products/krishna-omnibenevolent-3.jpg",
      "/products/krishna-omnibenevolent-4.jpg"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted White Marble with Jewels",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 61 cm (24 inch)",
      "Width: 30.5 cm (12 inch)",
      "Depth: 12.5 cm (5 inch)",
      "Weight: 28.20 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "shivalingam-black-small",
    name: "6\" Small Black Marble Shivalingam",
    deity: "Shiva — The Infinite Consciousness",
    price: 6600,
    originalPrice: 6600,
    material: "Black Marble",
    height: "6 inches",
    weight: "Handmade",
    description: "6\" Small Black Marble Shivalingam | Handcrafted | Sacred Puja Idol",
    longDescription: "A perfectly proportioned 6\" Small Black Marble Shivalingam, handcrafted from pure black stone. This sacred murti represents Lord Shiva in his most abstract and infinite form, ideal for daily puja and home mandir installation.",
    images: ["/products/shiva-lingam-hero.jpg", "/products/shiva-lingam-black.jpg"],
    rating: 5.0,
    reviews: 8,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Smooth Black Polish with Hand-painted Tripundra",
    origin: "MADE IN INDIA",
    features: [
      "6\" Small Black Marble Shivalingam",
      "Handmade Sacred Puja Idol",
      "Fully Insured Order",
      "100% Handmade in India",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "ganesha-dancing-large",
    name: "36\" Large Dancing Ganesha",
    deity: "Ganesha — Remover of Obstacles",
    price: 420000,
    originalPrice: 420000,
    material: "White Marble",
    height: "36 inches",
    weight: "Handmade",
    description: "36\" Large Dancing Ganesha | Handmade | White Marble Ganesha | Ganpati Statue",
    longDescription: "Exquisite 36\" Large Dancing Ganesha handmade from pure White Marble. A mesmerizing Ganpati Statue capturing the joyful dance of the Lord of New Beginnings.",
    images: [
      "/products/dancing-ganesha-hero.jpg",
      "/products/dancing-ganesha-1.jpg",
      "/products/dancing-ganesha-3.jpg"
    ],
    rating: 5.0,
    reviews: 12,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-polished White with Gold Accents",
    origin: "MADE IN INDIA",
    features: [
      "36\" Large Dancing Ganesha",
      "Handmade White Marble Ganpati Statue",
      "Fully Insured Order",
      "100% Handmade in India",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "ganesha-marble-01",
    name: "Shri Ganesha",
    deity: "Ganesha — Remover of Obstacles",
    price: 18999,
    originalPrice: 24000,
    material: "Makrana White Marble",
    height: "14 inches",
    weight: "3.2 kg",
    description: "Pure Makrana marble Ganesha with 24-karat gold leaf ornamentation — the ultimate auspicious blessing for any home.",
    longDescription: "Carved from the same pristine Makrana marble used in the Taj Mahal, this Ganesha murti radiates timeless purity and auspiciousness. Our master craftsmen from Jaipur spend 3–4 weeks on each piece, using both traditional chisels and precision instruments. The Lord is depicted in his classic seated Sukhasana form — four arms holding the parsha (axe), pasha (rope), modak, and offering abhaya (protection) mudra, with his sacred mouse (mushaka) at his feet. Intricate 24-karat gold leaf is applied to the crown, necklaces, and ornamental bands, adding divine luminescence that deepens over years of worship.",
    images: ["/products/ganesha-marble.jpg"],
    rating: 4.9,
    reviews: 312,
    inStock: true,
    badge: "Bestseller",
    category: "Marble",
    finish: "Hand-polished White with Gold Leaf",
    origin: "Jaipur, Rajasthan",
    features: [
      "Pure Makrana marble",
      "24-karat gold leaf accents",
      "Hand-chiseled by palace artisans",
      "Consecrated in Varanasi temple",
      "Padded mahogany presentation box",
    ],
  },
  {
    id: "durga-marble-01",
    name: "Maa Durga",
    deity: "Durga — The Invincible Goddess",
    price: 22500,
    originalPrice: 28000,
    material: "Makrana White Marble",
    height: "18 inches",
    weight: "4.8 kg",
    description: "Breathtaking white marble Durga Mata seated on her lion, wielding divine weapons — carved in the classical Rajput tradition.",
    longDescription: "This extraordinary Durga Mata murti is carved from the finest Makrana white marble by a family of sculptors whose lineage served the Rajput royal courts of Jaipur for seven generations. The Goddess is shown in her Mahishasuramardini form — triumphant, seated gracefully on her sacred lion (Simha), eight arms each holding a divine weapon: trishul, sword, bow, chakra, lotus, and bestowing both abhaya (fearlessness) and varada (boon-giving) blessings. The detailed folds of her garments and each strand of her crown's pearl strings are carved with microscopic precision. The pure white marble symbolizes the Goddess's transcendent purity and victory over darkness.",
    images: ["/products/durga-marble.jpg"],
    rating: 4.9,
    reviews: 187,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-polished White Marble",
    origin: "Jaipur, Rajasthan",
    features: [
      "Pure Makrana marble",
      "Royal court sculptor lineage",
      "Mahishasuramardini iconography",
      "Temple-consecrated",
      "Climate-controlled shipping crate",
    ],
  },
  {
    id: "krishna-brass-01",
    name: "Shri Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 16500,
    originalPrice: 21000,
    material: "Panchaloha Brass",
    height: "16 inches",
    weight: "3.6 kg",
    description: "Antique-finish brass Krishna with peacock crown, playing his divine flute — cast in the ancient Dhokra tradition.",
    longDescription: "This magnificent Krishna murti captures the Lord in his most beloved Venugopal (flute-playing) form — standing in the graceful Tribhanga posture, with his flute (bansuri) held to his lips, peacock feather crown, and the eternally divine smile that melts all hearts. Cast in Panchaloha brass using the lost-wax method perfected in Swamimalai over 2,000 years, the deep golden-bronze patina develops richer character with each passing year. The intricate surface detailing — from the individual feathers of his crown to the fine beadwork of his necklaces — took the master artisan over six weeks to complete by hand. Traditionally adorned with fresh jasmine and rose garlands during worship.",
    images: ["/products/krishna-brass.jpg"],
    rating: 4.8,
    reviews: 241,
    inStock: true,
    badge: "Customer Favourite",
    category: "Bronze",
    finish: "Antique Brass Patina",
    origin: "Swamimalai, Tamil Nadu",
    features: [
      "Panchaloha (5-metal alloy)",
      "Lost-wax Swamimalai casting",
      "Tribhanga Venugopal form",
      "Deepens with age beautifully",
      "Includes garland-ready hook",
    ],
  },
  {
    id: "lakshmi-bronze-01",
    name: "Maa Lakshmi",
    deity: "Lakshmi — Goddess of Prosperity",
    price: 19800,
    originalPrice: 25000,
    material: "Panchaloha Bronze",
    height: "15 inches",
    weight: "3.9 kg",
    description: "Dark Panchaloha bronze Lakshmi of museum calibre — Chola-style craftsmanship at its most sublime and serene.",
    longDescription: "This supreme Lakshmi murti is cast in the revered Chola bronze style, the pinnacle of Indian sculptural tradition — the very same tradition that produced the Nataraja sculptures now displayed in the world's greatest museums. The Goddess gazes inward with serene meditation (antarmukhi), her face reflecting the profound peace that comes from absolute wealth and grace. Every element adheres strictly to Agama Shastra proportions: the Urdhva-pundra tilak, the shankha-chakra earrings, the elaborate lotus-petal crown, and the intricate stacked necklaces. The dark Panchaloha develops a sacred black-gold patina over decades of worship, considered the highest form of the material. Each piece comes with a provenance certificate from our resident Agama Shastra scholar.",
    images: ["/products/lakshmi-bronze.jpg"],
    rating: 5.0,
    reviews: 98,
    inStock: true,
    badge: "Limited Edition",
    category: "Bronze",
    finish: "Sacred Dark Patina",
    origin: "Kumbakonam, Tamil Nadu",
    features: [
      "Museum-grade Chola style",
      "Agama Shastra compliant",
      "Develops sacred patina over years",
      "Scholar-certified iconography",
      "Velvet-lined mahogany chest",
    ],
  },
  {
    id: "shiva-crystal-01",
    name: "Shiva Lingam",
    deity: "Shiva — The Infinite Consciousness",
    price: 8999,
    originalPrice: 11500,
    material: "Narmada Sphatik Crystal",
    height: "6 inches",
    weight: "1.2 kg",
    description: "Natural Narmada Sphatik (crystal) Shiva Lingam, each one uniquely shaped by sacred river waters.",
    longDescription: "These sacred Sphatik Shiva Lingams are naturally formed in the Narmada River — one of India's holiest rivers. Each lingam is unique in its veining and translucency, shaped by millions of years of riverbed polishing. Sphatik (rock crystal quartz) is considered the purest manifestation of Lord Shiva's cosmic energy in the Shaiva tradition. The crystal's natural piezoelectric properties are believed to amplify meditation and prayer. Comes with a handcrafted brass yoni base, engraved with sacred geometric patterns.",
    images: ["/products/shiva-crystal.jpg"],
    rating: 4.9,
    reviews: 312,
    inStock: true,
    category: "Crystal",
    finish: "Natural Polished",
    origin: "Narmada River, Madhya Pradesh",
    features: [
      "100% natural Narmada crystal",
      "Unique formation per piece",
      "Brass yoni base included",
      "Comes with abhishek kit",
      "Vedic certification",
    ],
  },
  {
    id: "hanuman-pancha-01",
    name: "Panchamukhi Hanuman",
    deity: "Hanuman — The Devotee Supreme",
    price: 15750,
    originalPrice: 19000,
    material: "Panchaloha Bronze",
    height: "14 inches",
    weight: "3.1 kg",
    description: "Five-faced (Panchamukhi) Hanuman in Panchaloha bronze — a rare and powerful protective murti.",
    longDescription: "The Panchamukhi (five-faced) form of Hanuman is exceptionally rare in murti-making, as each face must be perfectly proportioned while maintaining devotional accuracy. The five faces — Hanuman (north), Narasimha (south), Garuda (west), Varaha (east), and Hayagriva (sky-facing) — represent mastery over all five directions and protection from all negative forces. This murti is cast by a fourth-generation master craftsman from Kumbakonam, Tamil Nadu, following strict Agama Shastra specifications. It is especially revered for installation at home entrances as a powerful protective deity.",
    images: ["/products/hanuman-bronze.jpg"],
    rating: 4.8,
    reviews: 203,
    inStock: false,
    badge: "Sold Out",
    category: "Bronze",
    finish: "Antique Bronze",
    origin: "Kumbakonam, Tamil Nadu",
    features: [
      "Panchamukhi (5-faced) form",
      "Agama Shastra compliant",
      "Protective home deity",
      "Consecrated with Vedic rituals",
      "Comes with puja guide",
    ],
  },
];

export const categories = ["All", "Bronze", "Marble", "Crystal", "Brass", "Wood"];

export const testimonials = [
  {
    name: "Priya Sharma",
    location: "Mumbai",
    text: "The Ganesha murti I received is breathtaking. The craftsmanship is extraordinary — I can see every individual detail. It now sits as the centerpiece of our home mandir.",
    rating: 5,
    avatar: "PS",
  },
  {
    name: "Rajesh Iyer",
    location: "Chennai",
    text: "As someone who has collected temple art for 20 years, I can say the quality here is museum-grade. The Lakshmi murti exceeded every expectation. The dark patina is divine.",
    rating: 5,
    avatar: "RI",
  },
  {
    name: "Dr. Anita Kulkarni",
    location: "Pune",
    text: "Ordered the Durga Mata for our puja room. The packaging was as luxurious as the murti itself. The marble is flawlessly pure. She was moved to tears — it's truly divine.",
    rating: 5,
    avatar: "AK",
  },
  {
    name: "Vikram Menon",
    location: "Bangalore",
    text: "The Krishna murti is the most beautiful thing in our home. The brass patina glows during evening aarti. Authenticity certificate gave complete confidence. Highly recommended.",
    rating: 5,
    avatar: "VM",
  },
];
