import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "ganesha-marble-01",
    name: "Shri Ganesha",
    deity: "Ganesha — Remover of Obstacles",
    price: 18999,
    originalPrice: 24000,
    material: "Makrana White Marble",
    height: "14 inches",
    weight: "3.2 kg",
    description: "Pure Makrana marble Ganesha with 24-karat gold leaf ornamentation — the ultimate auspicious blessing for any home.",
    longDescription: "Carved from the same pristine Makrana marble used in the Taj Mahal, this Ganesha murti radiates timeless purity and auspiciousness. Our master craftsmen from Jaipur spend 3–4 weeks on each piece, using both traditional chisels and precision instruments. The Lord is depicted in his classic seated Sukhasana form — four arms holding the parsha (axe), pasha (rope), modak, and offering abhaya (protection) mudra, with his sacred mouse (mushaka) at his feet. Intricate 24-karat gold leaf is applied to the crown, necklaces, and ornamental bands, adding divine luminescence that deepens over years of worship.",
    images: ["/products/ganesha-marble.jpg"],
    rating: 4.9,
    reviews: 312,
    inStock: true,
    badge: "Bestseller",
    category: "Marble",
    finish: "Hand-polished White with Gold Leaf",
    origin: "Jaipur, Rajasthan",
    features: [
      "Pure Makrana marble",
      "24-karat gold leaf accents",
      "Hand-chiseled by palace artisans",
      "Consecrated in Varanasi temple",
      "Padded mahogany presentation box",
    ],
  },
  {
    id: "durga-marble-01",
    name: "Maa Durga",
    deity: "Durga — The Invincible Goddess",
    price: 22500,
    originalPrice: 28000,
    material: "Makrana White Marble",
    height: "18 inches",
    weight: "4.8 kg",
    description: "Breathtaking white marble Durga Mata seated on her lion, wielding divine weapons — carved in the classical Rajput tradition.",
    longDescription: "This extraordinary Durga Mata murti is carved from the finest Makrana white marble by a family of sculptors whose lineage served the Rajput royal courts of Jaipur for seven generations. The Goddess is shown in her Mahishasuramardini form — triumphant, seated gracefully on her sacred lion (Simha), eight arms each holding a divine weapon: trishul, sword, bow, chakra, lotus, and bestowing both abhaya (fearlessness) and varada (boon-giving) blessings. The detailed folds of her garments and each strand of her crown's pearl strings are carved with microscopic precision. The pure white marble symbolizes the Goddess's transcendent purity and victory over darkness.",
    images: ["/products/durga-marble.jpg"],
    rating: 4.9,
    reviews: 187,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-polished White Marble",
    origin: "Jaipur, Rajasthan",
    features: [
      "Pure Makrana marble",
      "Royal court sculptor lineage",
      "Mahishasuramardini iconography",
      "Temple-consecrated",
      "Climate-controlled shipping crate",
    ],
  },
  {
    id: "krishna-brass-01",
    name: "Shri Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 16500,
    originalPrice: 21000,
    material: "Panchaloha Brass",
    height: "16 inches",
    weight: "3.6 kg",
    description: "Antique-finish brass Krishna with peacock crown, playing his divine flute — cast in the ancient Dhokra tradition.",
    longDescription: "This magnificent Krishna murti captures the Lord in his most beloved Venugopal (flute-playing) form — standing in the graceful Tribhanga posture, with his flute (bansuri) held to his lips, peacock feather crown, and the eternally divine smile that melts all hearts. Cast in Panchaloha brass using the lost-wax method perfected in Swamimalai over 2,000 years, the deep golden-bronze patina develops richer character with each passing year. The intricate surface detailing — from the individual feathers of his crown to the fine beadwork of his necklaces — took the master artisan over six weeks to complete by hand. Traditionally adorned with fresh jasmine and rose garlands during worship.",
    images: ["/products/krishna-brass.jpg"],
    rating: 4.8,
    reviews: 241,
    inStock: true,
    badge: "Customer Favourite",
    category: "Bronze",
    finish: "Antique Brass Patina",
    origin: "Swamimalai, Tamil Nadu",
    features: [
      "Panchaloha (5-metal alloy)",
      "Lost-wax Swamimalai casting",
      "Tribhanga Venugopal form",
      "Deepens with age beautifully",
      "Includes garland-ready hook",
    ],
  },
  {
    id: "lakshmi-bronze-01",
    name: "Maa Lakshmi",
    deity: "Lakshmi — Goddess of Prosperity",
    price: 19800,
    originalPrice: 25000,
    material: "Panchaloha Bronze",
    height: "15 inches",
    weight: "3.9 kg",
    description: "Dark Panchaloha bronze Lakshmi of museum calibre — Chola-style craftsmanship at its most sublime and serene.",
    longDescription: "This supreme Lakshmi murti is cast in the revered Chola bronze style, the pinnacle of Indian sculptural tradition — the very same tradition that produced the Nataraja sculptures now displayed in the world's greatest museums. The Goddess gazes inward with serene meditation (antarmukhi), her face reflecting the profound peace that comes from absolute wealth and grace. Every element adheres strictly to Agama Shastra proportions: the Urdhva-pundra tilak, the shankha-chakra earrings, the elaborate lotus-petal crown, and the intricate stacked necklaces. The dark Panchaloha develops a sacred black-gold patina over decades of worship, considered the highest form of the material. Each piece comes with a provenance certificate from our resident Agama Shastra scholar.",
    images: ["/products/lakshmi-bronze.jpg"],
    rating: 5.0,
    reviews: 98,
    inStock: true,
    badge: "Limited Edition",
    category: "Bronze",
    finish: "Sacred Dark Patina",
    origin: "Kumbakonam, Tamil Nadu",
    features: [
      "Museum-grade Chola style",
      "Agama Shastra compliant",
      "Develops sacred patina over years",
      "Scholar-certified iconography",
      "Velvet-lined mahogany chest",
    ],
  },
  {
    id: "shiva-crystal-01",
    name: "Shiva Lingam",
    deity: "Shiva — The Infinite Consciousness",
    price: 8999,
    originalPrice: 11500,
    material: "Narmada Sphatik Crystal",
    height: "6 inches",
    weight: "1.2 kg",
    description: "Natural Narmada Sphatik (crystal) Shiva Lingam, each one uniquely shaped by sacred river waters.",
    longDescription: "These sacred Sphatik Shiva Lingams are naturally formed in the Narmada River — one of India's holiest rivers. Each lingam is unique in its veining and translucency, shaped by millions of years of riverbed polishing. Sphatik (rock crystal quartz) is considered the purest manifestation of Lord Shiva's cosmic energy in the Shaiva tradition. The crystal's natural piezoelectric properties are believed to amplify meditation and prayer. Comes with a handcrafted brass yoni base, engraved with sacred geometric patterns.",
    images: ["/products/shiva-crystal.jpg"],
    rating: 4.9,
    reviews: 312,
    inStock: true,
    category: "Crystal",
    finish: "Natural Polished",
    origin: "Narmada River, Madhya Pradesh",
    features: [
      "100% natural Narmada crystal",
      "Unique formation per piece",
      "Brass yoni base included",
      "Comes with abhishek kit",
      "Vedic certification",
    ],
  },
  {
    id: "hanuman-pancha-01",
    name: "Panchamukhi Hanuman",
    deity: "Hanuman — The Devotee Supreme",
    price: 15750,
    originalPrice: 19000,
    material: "Panchaloha Bronze",
    height: "14 inches",
    weight: "3.1 kg",
    description: "Five-faced (Panchamukhi) Hanuman in Panchaloha bronze — a rare and powerful protective murti.",
    longDescription: "The Panchamukhi (five-faced) form of Hanuman is exceptionally rare in murti-making, as each face must be perfectly proportioned while maintaining devotional accuracy. The five faces — Hanuman (north), Narasimha (south), Garuda (west), Varaha (east), and Hayagriva (sky-facing) — represent mastery over all five directions and protection from all negative forces. This murti is cast by a fourth-generation master craftsman from Kumbakonam, Tamil Nadu, following strict Agama Shastra specifications. It is especially revered for installation at home entrances as a powerful protective deity.",
    images: ["/products/hanuman-bronze.jpg"],
    rating: 4.8,
    reviews: 203,
    inStock: false,
    badge: "Sold Out",
    category: "Bronze",
    finish: "Antique Bronze",
    origin: "Kumbakonam, Tamil Nadu",
    features: [
      "Panchamukhi (5-faced) form",
      "Agama Shastra compliant",
      "Protective home deity",
      "Consecrated with Vedic rituals",
      "Comes with puja guide",
    ],
  },
];

export const categories = ["All", "Bronze", "Marble", "Crystal", "Brass", "Wood"];

export const testimonials = [
  {
    name: "Priya Sharma",
    location: "Mumbai",
    text: "The Ganesha murti I received is breathtaking. The craftsmanship is extraordinary — I can see every individual detail. It now sits as the centerpiece of our home mandir.",
    rating: 5,
    avatar: "PS",
  },
  {
    name: "Rajesh Iyer",
    location: "Chennai",
    text: "As someone who has collected temple art for 20 years, I can say the quality here is museum-grade. The Lakshmi murti exceeded every expectation. The dark patina is divine.",
    rating: 5,
    avatar: "RI",
  },
  {
    name: "Dr. Anita Kulkarni",
    location: "Pune",
    text: "Ordered the Durga Mata for our puja room. The packaging was as luxurious as the murti itself. The marble is flawlessly pure. She was moved to tears — it's truly divine.",
    rating: 5,
    avatar: "AK",
  },
  {
    name: "Vikram Menon",
    location: "Bangalore",
    text: "The Krishna murti is the most beautiful thing in our home. The brass patina glows during evening aarti. Authenticity certificate gave complete confidence. Highly recommended.",
    rating: 5,
    avatar: "VM",
  },
];
